# Generated by Django 5.1.3 on 2024-11-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert_disasteralert_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, choices=[('girne', 'Girne'), ('lefkoşa', 'Lefkoşa'), ('lefke', 'Lefke'), ('iskele', 'İskele'), ('gazimağusa', 'Gazimağusa'), ('güzelyurt', 'Güzelyurt')], max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
